In [1]:
#Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set_style("whitegrid")

In [2]:
#Loading the dataset
df = pd.read_csv("../data/German_Credit.csv")

In [3]:
#Understanding the structure and basic properties of the dataset.
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1000 non-null   int64
 1   Sex               1000 non-null   object
 2   Job               1000 non-null   object
 3   Housing           1000 non-null   object
 4   Saving accounts   1000 non-null   object
 5   Checking account  1000 non-null   object
 6   Credit amount     1000 non-null   int64
 7   Duration          1000 non-null   int64
 8   Risk              1000 non-null   int64
 9   Purpose           1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

The Data Structure:

- Total rows: 1000
- Total columns: 10
- Target variable: `Risk` (1 = good, 0 = bad)
- Feature types:
  - Numeric: Age, Credit amount, Duration, Risk
  - Categorical: Sex, Job, Housing, Saving accounts, Checking account, Purpose

Observation:
- No missing values detected
- Data types are mostly correct
- Some columns have spaces in names (e.g., `Saving accounts`), so it needs to be cleaned by using _ instead of space.

In [4]:
# Missing values
df.isna().sum()
# Duplicates
df.duplicated().sum()

# Statistical summary
df.describe(include='all')

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Risk,Purpose
count,1000.000000,1000,1000,1000,1000,1000,1000.000000,1000.000000,1000.000000,1000
unique,NaN,2,3,3,4,3,NaN,NaN,NaN,8
top,NaN,male,skilled,own,little,moderate,NaN,NaN,NaN,car
freq,NaN,690,630,713,786,472,NaN,NaN,NaN,337
mean,35.546000,NaN,NaN,NaN,NaN,NaN,3271.258000,20.903000,0.300000,NaN
std,11.375469,NaN,NaN,NaN,NaN,NaN,2822.736876,12.058814,0.458487,NaN
min,19.000000,NaN,NaN,NaN,NaN,NaN,250.000000,4.000000,0.000000,NaN
25%,27.000000,NaN,NaN,NaN,NaN,NaN,1365.500000,12.000000,0.000000,NaN
50%,33.000000,NaN,NaN,NaN,NaN,NaN,2319.500000,18.000000,0.000000,NaN
75%,42.000000,NaN,NaN,NaN,NaN,NaN,3972.250000,24.000000,1.000000,NaN
max,75.000000,NaN,NaN,NaN,NaN,NaN,18424.000000,72.000000,1.000000,NaN

In [5]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [6]:
df.columns

Index(['age', 'sex', 'job', 'housing', 'saving_accounts', 'checking_account',
       'credit_amount', 'duration', 'risk', 'purpose'],
      dtype='object')

In [7]:
df.rename(columns={
    'saving_accounts': 'saving_account'
}, inplace=True)

In [8]:
#Check missing values
df.isna().sum().sort_values(ascending=False)

age                 0
sex                 0
job                 0
housing             0
saving_account      0
checking_account    0
credit_amount       0
duration            0
risk                0
purpose             0
dtype: int64

In [9]:
#confirming datatypes
df.dtypes

age                  int64
sex                 object
job                 object
housing             object
saving_account      object
checking_account    object
credit_amount        int64
duration             int64
risk                 int64
purpose             object
dtype: object

In [10]:
df['age'].min(), df['age'].max()
df['duration'].min(), df['duration'].max()
df['credit_amount'].min(), df['credit_amount'].max()
df['risk'].value_counts(normalize=True)

risk
0    0.7
1    0.3
Name: proportion, dtype: float64

In [11]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[18, 34, 64, 75],
    labels=['Young', 'Middle-aged', 'Retired'],
    include_lowest=True
)

In [12]:
df['credit_per_month'] = df['credit_amount'] / df['duration']

In [14]:
# df['has_savings'] = df['saving_accounts'].apply(lambda x: 'Yes' if x != 'none' else 'No')
# df['has_checking'] = df['checking_account'].apply(lambda x: 'Yes' if x != 'none' else 'No')


saving_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}
checking_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}

df['saving_score'] = df['saving_account'].map(saving_map)
df['checking_score'] = df['checking_account'].map(checking_map)

In [15]:
df.head()

,age,sex,job,housing,saving_account,checking_account,credit_amount,duration,risk,purpose,age_group,credit_per_month,saving_score,checking_score
0,67,male,skilled,own,little,little,1169,6,0,radio/TV,Retired,194.833333,1,1
1,22,female,skilled,own,little,moderate,5951,48,1,radio/TV,Young,123.979167,1,2
2,49,male,unskilled_and_non-resident,own,little,little,2096,12,0,education,Middle-aged,174.666667,1,1
3,45,male,skilled,free,little,little,7882,42,0,furniture/equipment,Middle-aged,187.666667,1,1
4,53,male,skilled,free,little,little,4870,24,1,car,Middle-aged,202.916667,1,1

In [16]:
df.describe()

,age,credit_amount,duration,risk,credit_per_month,saving_score,checking_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,35.546000,3271.258000,20.903000,0.300000,167.687020,1.388000,1.598000
std,11.375469,2822.736876,12.058814,0.458487,153.490959,0.843901,0.605609
min,19.000000,250.000000,4.000000,0.000000,24.055556,1.000000,1.000000
25%,27.000000,1365.500000,12.000000,0.000000,89.600000,1.000000,1.000000
50%,33.000000,2319.500000,18.000000,0.000000,130.333333,1.000000,2.000000
75%,42.000000,3972.250000,24.000000,1.000000,206.183333,1.000000,2.000000
max,75.000000,18424.000000,72.000000,1.000000,2482.666667,4.000000,3.000000

In [17]:
df.value_counts()

age  sex     job                         housing  saving_account  checking_account  credit_amount  duration  risk  purpose              age_group  credit_per_month  saving_score  checking_score
19   female  skilled                     rent     little          little            1980           9         1     furniture/equipment  Young      220.000000        1             1                 1
             unskilled_and_non-resident  rent     rich            moderate          983            12        0     furniture/equipment  Young      81.916667         3             2                 1
20   female  skilled                     own      little          moderate          1967           24        0     radio/TV             Young      81.958333         1             2                 1
                                                  rich            moderate          1577           11        0     furniture/equipment  Young      143.363636        3             2                 1
                                         rent     little          little            1282           12        1     furniture/equipment  Young      106.833333        1             1                 1
                                                                                                                                                                                                    ..
74   male    highly skilled              own      little          little            4526           24        0     business             Retired    188.583333        1             1                 1
             unskilled_and_non-resident  own      little          little            3448           5         0     business             Retired    689.600000        1             1                 1
                                                                  rich              1299           6         0     car                  Retired    216.500000        1             3                 1
75   female  highly skilled              own      little          little            1374           6         0     car                  Retired    229.000000        1             1                 1
     male    highly skilled              free     little          little            6615           24        0     car                  Retired    275.625000        1             1                 1
Name: count, Length: 1000, dtype: int64

In [18]:
df.head()
df.tail()
df.sample(5)
df.describe()

,age,credit_amount,duration,risk,credit_per_month,saving_score,checking_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,35.546000,3271.258000,20.903000,0.300000,167.687020,1.388000,1.598000
std,11.375469,2822.736876,12.058814,0.458487,153.490959,0.843901,0.605609
min,19.000000,250.000000,4.000000,0.000000,24.055556,1.000000,1.000000
25%,27.000000,1365.500000,12.000000,0.000000,89.600000,1.000000,1.000000
50%,33.000000,2319.500000,18.000000,0.000000,130.333333,1.000000,2.000000
75%,42.000000,3972.250000,24.000000,1.000000,206.183333,1.000000,2.000000
max,75.000000,18424.000000,72.000000,1.000000,2482.666667,4.000000,3.000000

In [19]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  '#Importing necessary libraries\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\npd.set_option(\'display.max_columns\', None)\nsns.set_style("whitegrid")',
  '#Loading the dataset\ndf = pd.read_csv("../data/German_Credit.csv")',
  '#Understanding the structure and basic properties of the dataset.\ndf.head()\ndf.shape\ndf.info()',
  "# Missing values\ndf.isna().sum()\n# Duplicates\ndf.duplicated().sum()\n\n# Statistical summary\ndf.describe(include='all')",
  'df.columns = (\n    df.columns\n      .str.strip()\n      .str.lower()\n      .str.replace(" ", "_")\n)',
  'df.columns',
  "df.rename(columns={\n    'saving_accounts': 'saving_account'\n}, inplace=True)",
  '#Check missing values\ndf.isna().sum().sort_values(ascending=False)',
  '#confirming datatypes\ndf.dtypes',
  "df['age'].min(), df['age'].max()\ndf['duration'].min(), df['duration'].max()\ndf['credit_amount'].min(), df['credit_amount'].max()\ndf['risk'].value_counts(normalize=True)",
  "df['age_group'] = pd.cut(\n    df['age'],\n    bins=[18, 34, 64, 75],\n    labels=['Young', 'Middle-aged', 'Retired'],\n    include_lowest=True\n)",
  "df['credit_per_month'] = df['credit_amount'] / df['duration']",
  "# df['has_savings'] = df['saving_accounts'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n# df['has_checking'] = df['checking_account'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n\n\nsaving_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\nchecking_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\n\ndf['saving_score'] = df['saving_account'].map(saving_map)\ndf['checking_score'] = df['checking_account'].map(checking_map)",
  "# df['has_savings'] = df['saving_accounts'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n# df['has_checking'] = df['checking_account'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n\n\nsaving_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\nchecking_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\n\ndf['saving_score'] = df['saving_account'].map(saving_map)\ndf['checking_score'] = df['checking_account'].map(checking_map)",
  'df.head()',
  'df.describe()',
  'df.value_counts()',
  'df.head()\ndf.tail()\ndf.sample(5)\ndf.describe()',
  'globals()'],
 '_oh': {4:                 Age   Sex      Job Housing Saving accounts Checking account  \
  count   1000.000000  1000     1000    1000            1000             1000
  unique          NaN     2        3       3               4                3
  top             NaN  male  skilled     own          little         moderate
  freq            NaN   690      630     713             786              472
  mean      35.546000   NaN      NaN     NaN             NaN              NaN
  std       11.375469   NaN      NaN     NaN             NaN              NaN
  min       19.000000   NaN      NaN     NaN             NaN              NaN
  25%       27.000000   NaN      NaN     NaN             NaN              NaN
  50%       33.000000   NaN      NaN     NaN             NaN              NaN
  75%       42.000000   NaN      NaN     NaN             NaN              NaN
  max       75.000000   NaN      NaN     NaN             NaN              NaN

          Credit amount     Duration         Risk Purpose
  count     1000.000000  1000.000000  1000.000000    1000
  unique            NaN          NaN          NaN       8
  top               NaN          NaN          NaN     car
  freq              NaN          NaN          NaN     337
  mean      3271.258000    20.903000     0.300000     NaN
  std       2822.736876    12.058814     0.458487     NaN
  min        250.000000     4.000000     0.000000     NaN
  25%       1365.500000    12.000000     0.000000     NaN
  50%       2319.500000    18.000000     0.000000     NaN
  75%       3972.250000    24.000000     1.000000     NaN
  max      18424.000000    72.000000     1.000000     NaN  ,
  6: Index(['age', 'sex', 'job', 'housing', 'saving_accounts', 'checking_account',
         'credit_amount', 'duration', 'risk', 'purpose'],
        dtype='object'),
  8: age                 0
  sex                 0
  job                 0
  housing             0
  saving_account      0
  checking_account    0
  credit_amount       0
  duration            0
  risk                0
  purpose             0
  dtype: int64,
  9: age                  int64
  sex                 object
  job                 object
  housing             object
  saving_account      object
  checking_account    object
  credit_amount        int64
  duration             int64
  risk                 int64
  purpose             object
  dtype: object,
  10: risk
  0    0.7
  1    0.3
  Name: proportion, dtype: float64,
  15:    age     sex                         job housing saving_account  \
  0   67    male                     skilled     own         little
  1   22  female                     skilled     own         little
  2   49    male  unskilled_and_non-resident     own         little
  3   45    male                     skilled    free         little
  4   53    male                     skilled    free         little

    checking_account  credit_amount  duration  risk              purpose  \
  0           little           1169         6     0             radio/TV
  1         moderate           5951        48     1             radio/TV
  2           little           2096        12     0            education
  3           little           7882        42     0  furniture/equipment
  4           little           4870        24     1                  car

       age_group  credit_per_month  saving_score  checking_score
  0      Retired        194.833333             1               1
  1        Young        123.979167             1               2
  2  Middle-aged        174.666667             1               1
  3  Middle-aged        187.666667             1               1
  4  Middle-aged        202.916667             1               1  ,
  16:                age  credit_amount     duration         risk  credit_per_month  \
  count  1000.000000    1000.000000  1000.000000  1000.000000       1000.000000
  mean     35.546000    3271.258000    20.903000     0.300000        167.687020
  std      11.375469    2822.736876    12.058814     0.458487        153.490959
  min      19.000000     250.000000     4.000000     0.000000         24.055556
  25%      27.000000    1365.500000    12.000000     0.000000         89.600000
  50%      33.000000    2319.500000    18.000000     0.000000        130.333333
  75%      42.000000    3972.250000    24.000000     1.000000        206.183333
  max      75.000000   18424.000000    72.000000     1.000000       2482.666667

         saving_score  checking_score
  count   1000.000000     1000.000000
  mean       1.388000        1.598000
  std        0.843901        0.605609
  min        1.000000        1.000000
  25%        1.000000        1.000000
  50%        1.000000        2.000000
  75%        1.000000        2.000000
  max        4.000000        3.000000  ,
  17: age  sex     job                         housing  saving_account  checking_account  credit_amount  duration  risk  purpose              age_group  credit_per_month  saving_score  checking_score
  19   female  skilled                     rent     little          little            1980           9         1     furniture/equipment  Young      220.000000        1             1                 1
               unskilled_and_non-resident  rent     rich            moderate          983            12        0     furniture/equipment  Young      81.916667         3             2                 1
  20   female  skilled                     own      little          moderate          1967           24        0     radio/TV             Young      81.958333         1             2                 1
                                                    rich            moderate          1577           11        0     furniture/equipment  Young      143.363636        3             2                 1
                                           rent     little          little            1282           12        1     furniture/equipment  Young      106.833333        1             1                 1
                                                                                                                                                                                                      ..
  74   male    highly skilled              own      little          little            4526           24        0     business             Retired    188.583333        1             1                 1
               unskilled_and_non-resident  own      little          little            3448           5         0     business             Retired    689.600000        1             1                 1
                                                                    rich              1299           6         0     car                  Retired    216.500000        1             3                 1
  75   female  highly skilled              own      little          little            1374           6         0     car                  Retired    229.000000        1             1                 1
       male    highly skilled              free     little          little            6615           24        0     car                  Retired    275.625000        1             1                 1
  Name: count, Length: 1000, dtype: int64,
  18:                age  credit_amount     duration         risk  credit_per_month  \
  count  1000.000000    1000.000000  1000.000000  1000.000000       1000.000000
  mean     35.546000    3271.258000    20.903000     0.300000        167.687020
  std      11.375469    2822.736876    12.058814     0.458487        153.490959
  min      19.000000     250.000000     4.000000     0.000000         24.055556
  25%      27.000000    1365.500000    12.000000     0.000000         89.600000
  50%      33.000000    2319.500000    18.000000     0.000000        130.333333
  75%      42.000000    3972.250000    24.000000     1.000000        206.183333
  max      75.000000   18424.000000    72.000000     1.000000       2482.666667

         saving_score  checking_score
  count   1000.000000     1000.000000
  mean       1.388000        1.598000
  std        0.843901        0.605609
  min        1.000000        1.000000
  25%        1.000000        1.000000
  50%        1.000000        2.000000
  75%        1.000000        2.000000
  max        4.000000        3.000000  },
 '_dh': [WindowsPath('c:/Users/User/Desktop/Credit_Risk_Analysis/notebooks')],
 'In': ['',
  '#Importing necessary libraries\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\npd.set_option(\'display.max_columns\', None)\nsns.set_style("whitegrid")',
  '#Loading the dataset\ndf = pd.read_csv("../data/German_Credit.csv")',
  '#Understanding the structure and basic properties of the dataset.\ndf.head()\ndf.shape\ndf.info()',
  "# Missing values\ndf.isna().sum()\n# Duplicates\ndf.duplicated().sum()\n\n# Statistical summary\ndf.describe(include='all')",
  'df.columns = (\n    df.columns\n      .str.strip()\n      .str.lower()\n      .str.replace(" ", "_")\n)',
  'df.columns',
  "df.rename(columns={\n    'saving_accounts': 'saving_account'\n}, inplace=True)",
  '#Check missing values\ndf.isna().sum().sort_values(ascending=False)',
  '#confirming datatypes\ndf.dtypes',
  "df['age'].min(), df['age'].max()\ndf['duration'].min(), df['duration'].max()\ndf['credit_amount'].min(), df['credit_amount'].max()\ndf['risk'].value_counts(normalize=True)",
  "df['age_group'] = pd.cut(\n    df['age'],\n    bins=[18, 34, 64, 75],\n    labels=['Young', 'Middle-aged', 'Retired'],\n    include_lowest=True\n)",
  "df['credit_per_month'] = df['credit_amount'] / df['duration']",
  "# df['has_savings'] = df['saving_accounts'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n# df['has_checking'] = df['checking_account'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n\n\nsaving_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\nchecking_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\n\ndf['saving_score'] = df['saving_account'].map(saving_map)\ndf['checking_score'] = df['checking_account'].map(checking_map)",
  "# df['has_savings'] = df['saving_accounts'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n# df['has_checking'] = df['checking_account'].apply(lambda x: 'Yes' if x != 'none' else 'No')\n\n\nsaving_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\nchecking_map = {'none': 0, 'little': 1, 'moderate': 2, 'rich': 3, 'quite rich': 4}\n\ndf['saving_score'] = df['saving_account'].map(saving_map)\ndf['checking_score'] = df['checking_account'].map(checking_map)",
  'df.head()',
  'df.describe()',
  'df.value_counts()',
  'df.head()\ndf.tail()\ndf.sample(5)\ndf.describe()',
  'globals()'],
 'Out': {4:                 Age   Sex      Job Housing Saving accounts Checking account  \
  count   1000.000000  1000     1000    1000            1000             1000
  unique          NaN     2        3       3               4                3
  top             NaN  male  skilled     own          little         moderate
  freq            NaN   690      630     713             786              472
  mean      35.546000   NaN      NaN     NaN             NaN              NaN
  std       11.375469   NaN      NaN     NaN             NaN              NaN
  min       19.000000   NaN      NaN     NaN             NaN              NaN
  25%       27.000000   NaN      NaN     NaN             NaN              NaN
  50%       33.000000   NaN      NaN     NaN             NaN              NaN
  75%       42.000000   NaN      NaN     NaN             NaN              NaN
  max       75.000000   NaN      NaN     NaN             NaN              NaN

          Credit amount     Duration         Risk Purpose
  count     1000.000000  1000.000000  1000.000000    1000
  unique            NaN          NaN          NaN       8
  top               NaN          NaN          NaN     car
  freq              NaN          NaN          NaN     337
  mean      3271.258000    20.903000     0.300000     NaN
  std       2822.736876    12.058814     0.458487     NaN
  min        250.000000     4.000000     0.000000     NaN
  25%       1365.500000    12.000000     0.000000     NaN
  50%       2319.500000    18.000000     0.000000     NaN
  75%       3972.250000    24.000000     1.000000     NaN
  max      18424.000000    72.000000     1.000000     NaN  ,
  6: Index(['age', 'sex', 'job', 'housing', 'saving_accounts', 'checking_account',
         'credit_amount', 'duration', 'risk', 'purpose'],
        dtype='object'),
  8: age                 0
  sex                 0
  job                 0
  housing             0
  saving_account      0
  checking_account    0
  credit_amount       0
  duration            0
  risk                0
  purpose             0
  dtype: int64,
  9: age                  int64
  sex                 object
  job                 object
  housing             object
  saving_account      object
  checking_account    object
  credit_amount        int64
  duration             int64
  risk                 int64
  purpose             object
  dtype: object,
  10: risk
  0    0.7
  1    0.3
  Name: proportion, dtype: float64,
  15:    age     sex                         job housing saving_account  \
  0   67    male                     skilled     own         little
  1   22  female                     skilled     own         little
  2   49    male  unskilled_and_non-resident     own         little
  3   45    male                     skilled    free         little
  4   53    male                     skilled    free         little

    checking_account  credit_amount  duration  risk              purpose  \
  0           little           1169         6     0             radio/TV
  1         moderate           5951        48     1             radio/TV
  2           little           2096        12     0            education
  3           little           7882        42     0  furniture/equipment
  4           little           4870        24     1                  car

       age_group  credit_per_month  saving_score  checking_score
  0      Retired        194.833333             1               1
  1        Young        123.979167             1               2
  2  Middle-aged        174.666667             1               1
  3  Middle-aged        187.666667             1               1
  4  Middle-aged        202.916667             1               1  ,
  16:                age  credit_amount     duration         risk  credit_per_month  \
  count  1000.000000    1000.000000  1000.000000  1000.000000       1000.000000
  mean     35.546000    3271.258000    20.903000     0.300000        167.687020
  std      11.375469    2822.736876    12.058814     0.458487        153.490959
  min      19.000000     250.000000     4.000000     0.000000         24.055556
  25%      27.000000    1365.500000    12.000000     0.000000         89.600000
  50%      33.000000    2319.500000    18.000000     0.000000        130.333333
  75%      42.000000    3972.250000    24.000000     1.000000        206.183333
  max      75.000000   18424.000000    72.000000     1.000000       2482.666667

         saving_score  checking_score
  count   1000.000000     1000.000000
  mean       1.388000        1.598000
  std        0.843901        0.605609
  min        1.000000        1.000000
  25%        1.000000        1.000000
  50%        1.000000        2.000000
  75%        1.000000        2.000000
  max        4.000000        3.000000  ,
  17: age  sex     job                         housing  saving_account  checking_account  credit_amount  duration  risk  purpose              age_group  credit_per_month  saving_score  checking_score
  19   female  skilled                     rent     little          little            1980           9         1     furniture/equipment  Young      220.000000        1             1                 1
               unskilled_and_non-resident  rent     rich            moderate          983            12        0     furniture/equipment  Young      81.916667         3             2                 1
  20   female  skilled                     own      little          moderate          1967           24        0     radio/TV             Young      81.958333         1             2                 1
                                                    rich            moderate          1577           11        0     furniture/equipment  Young      143.363636        3             2                 1
                                           rent     little          little            1282           12        1     furniture/equipment  Young      106.833333        1             1                 1
                                                                                                                                                                                                      ..
  74   male    highly skilled              own      little          little            4526           24        0     business             Retired    188.583333        1             1                 1
               unskilled_and_non-resident  own      little          little            3448           5         0     business             Retired    689.600000        1             1                 1

In [20]:
df.to_csv("../data/processed_German_credit.csv", index=False)